"""
Transparency and Public Documentation.

Implements transparency requirements per EU AI Act Article 52.

EU AI Act Requirements for LIMITED RISK systems:
- Users must be informed they are interacting with AI
- System capabilities and limitations must be documented
- Decision-making process must be explainable

This module provides:
- Public-facing documentation generation
- System capability disclosure
- Limitation documentation
- Transparency reports

Addresses audit gap C4.3 (Transparency): +12 points target
"""

from datetime import datetime, timedelta
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field, computed_field
from enum import Enum

import structlog

logger = structlog.get_logger(__name__)


# ============================================================================
# ENUMS
# ============================================================================


class TransparencyLevel(str, Enum):
    """Level of transparency/disclosure."""
    FULL = "full"              # Complete disclosure
    SUMMARY = "summary"        # High-level overview
    MINIMAL = "minimal"        # Basic disclosure only
    CONFIDENTIAL = "confidential"  # Internal only


class DocumentationType(str, Enum):
    """Types of transparency documentation."""
    SYSTEM_OVERVIEW = "system_overview"
    CAPABILITIES = "capabilities"
    LIMITATIONS = "limitations"
    DATA_USAGE = "data_usage"
    DECISION_PROCESS = "decision_process"
    FAIRNESS_REPORT = "fairness_report"
    MODEL_CARD = "model_card"


# ============================================================================
# TRANSPARENCY SCHEMAS
# ============================================================================


class AIDisclosure(BaseModel):
    """AI system disclosure statement."""
    
    system_name: str = Field(description="Name of the AI system")
    is_ai_powered: bool = Field(default=True, description="Confirms AI-powered")
    
    disclosure_text: str = Field(
        default=(
            "RISKCAST is an AI-powered decision support system. "
            "All recommendations are generated by artificial intelligence "
            "and should be reviewed by human decision-makers before action. "
            "You have the right to request human review of any recommendation."
        ),
        description="Standard AI disclosure text",
    )
    
    human_oversight: str = Field(
        default="Human oversight is provided for all high-value decisions.",
        description="Human oversight statement",
    )
    
    contact_for_questions: str = Field(
        default="For questions about AI recommendations, contact support@company.com",
        description="Contact information",
    )


class SystemCapabilities(BaseModel):
    """Documentation of system capabilities."""
    
    # Core capabilities
    primary_function: str = Field(
        default="Supply chain risk decision support",
        description="Primary system function",
    )
    
    capabilities: List[str] = Field(
        default=[
            "Detect supply chain disruption signals from multiple sources",
            "Correlate signals with real-world observations (AIS, freight rates)",
            "Assess impact on customer shipments with confidence intervals",
            "Generate actionable recommendations with cost/benefit analysis",
            "Provide uncertainty quantification for all numeric outputs",
            "Track and calibrate prediction accuracy over time",
        ],
        description="List of system capabilities",
    )
    
    # Supported scenarios
    supported_scenarios: List[str] = Field(
        default=[
            "Red Sea / Suez Canal disruptions",
            "Panama Canal restrictions",
            "Major port congestion events",
            "Carrier service disruptions",
            "Freight rate volatility",
        ],
        description="Scenarios the system handles",
    )
    
    # Geographic coverage
    geographic_coverage: List[str] = Field(
        default=[
            "Asia-Pacific trade routes",
            "Europe-Middle East-Africa routes",
            "Trans-Pacific routes",
            "Trans-Atlantic routes",
        ],
        description="Geographic coverage areas",
    )
    
    # Data sources
    data_sources: List[str] = Field(
        default=[
            "Polymarket prediction markets (real-time signals)",
            "AIS vessel tracking (vessel positions)",
            "Freight rate indices (market conditions)",
            "Port congestion data (port status)",
            "News and events (situational awareness)",
        ],
        description="Data sources used",
    )
    
    # Output types
    output_types: List[str] = Field(
        default=[
            "7-Question Decision Framework",
            "Confidence intervals (80%, 90%, 95%, 99%)",
            "Cost/benefit analysis with uncertainty",
            "Alternative action recommendations",
            "Actionable guidance with deadlines",
        ],
        description="Types of outputs produced",
    )


class SystemLimitations(BaseModel):
    """Documentation of system limitations."""
    
    # Technical limitations
    technical_limitations: List[str] = Field(
        default=[
            "Dependent on external data source availability (Polymarket, AIS)",
            "Signal quality affects prediction accuracy",
            "Limited historical data for novel disruption types",
            "Models may underestimate tail risks in unprecedented scenarios",
            "Real-time data may have latency of up to 15 minutes",
        ],
        description="Technical limitations",
    )
    
    # Scope limitations
    scope_limitations: List[str] = Field(
        default=[
            "Does NOT provide autonomous execution - human decision required",
            "Does NOT cover medical, financial trading, or personal safety decisions",
            "Does NOT guarantee outcomes - recommendations are probabilistic",
            "Does NOT replace professional logistics expertise",
            "Limited to supported geographic regions and trade routes",
        ],
        description="Scope limitations",
    )
    
    # Data limitations
    data_limitations: List[str] = Field(
        default=[
            "Prediction market liquidity affects signal reliability",
            "AIS coverage varies by region",
            "Historical data limited to past 3 years",
            "Customer-specific factors may not be fully captured",
        ],
        description="Data-related limitations",
    )
    
    # Performance caveats
    performance_caveats: List[str] = Field(
        default=[
            "Accuracy varies by disruption type and region",
            "Confidence intervals are estimates, not guarantees",
            "Calibration is continuously improving but not perfect",
            "Past performance does not guarantee future accuracy",
        ],
        description="Performance caveats",
    )
    
    # When NOT to use
    not_suitable_for: List[str] = Field(
        default=[
            "Life-safety decisions",
            "Financial trading or investment decisions",
            "Legal or compliance decisions without professional review",
            "Situations requiring guaranteed outcomes",
            "Scenarios outside supported geographic coverage",
        ],
        description="Unsuitable use cases",
    )


class DataUsageDisclosure(BaseModel):
    """Documentation of data usage practices."""
    
    # Data collected
    data_collected: List[str] = Field(
        default=[
            "Customer shipment information (routes, values, timing)",
            "Decision feedback (outcomes, accuracy)",
            "Usage patterns (anonymized)",
        ],
        description="Types of data collected",
    )
    
    # Data purposes
    data_purposes: List[str] = Field(
        default=[
            "Generate personalized recommendations",
            "Improve prediction accuracy through calibration",
            "Monitor fairness and bias",
            "Comply with regulatory requirements",
        ],
        description="Purposes for data use",
    )
    
    # Data retention
    data_retention: str = Field(
        default=(
            "Decision records: 3 years. "
            "Audit logs: 7 years. "
            "Anonymized analytics: indefinite."
        ),
        description="Data retention policy",
    )
    
    # User rights
    user_rights: List[str] = Field(
        default=[
            "Right to explanation of any decision",
            "Right to request human review",
            "Right to access your data",
            "Right to correction of inaccurate data",
            "Right to deletion (subject to legal requirements)",
        ],
        description="User data rights",
    )
    
    # Data sharing
    data_sharing: str = Field(
        default=(
            "Customer data is not sold or shared with third parties for marketing. "
            "Anonymized, aggregated data may be used for system improvement. "
            "Data may be disclosed as required by law."
        ),
        description="Data sharing policy",
    )


class DecisionProcessDocumentation(BaseModel):
    """Documentation of the decision-making process."""
    
    # Process overview
    process_overview: str = Field(
        default=(
            "RISKCAST uses a 6-layer reasoning architecture to transform signals "
            "into decisions: (1) Factual analysis, (2) Causal reasoning, "
            "(3) Temporal assessment, (4) Counterfactual analysis, "
            "(5) Strategic evaluation, (6) Meta-cognitive review. "
            "All outputs include uncertainty quantification and are presented "
            "in a 7-Question framework for clear, actionable guidance."
        ),
        description="Overview of decision process",
    )
    
    # Key components
    key_components: List[str] = Field(
        default=[
            "OMEN: Signal detection and validation",
            "ORACLE: Reality correlation with ground truth",
            "RISKCAST: Decision composition with 7 Questions",
            "Uncertainty Module: Confidence intervals and calibration",
            "Governance: Policy enforcement and ethics checks",
        ],
        description="Key system components",
    )
    
    # How decisions are made
    decision_factors: List[str] = Field(
        default=[
            "Signal probability from prediction markets",
            "Correlation with vessel movements and freight rates",
            "Customer shipment exposure and timing",
            "Historical accuracy for similar scenarios",
            "Cost/benefit analysis with uncertainty",
        ],
        description="Factors influencing decisions",
    )
    
    # What decisions are NOT based on
    not_considered: List[str] = Field(
        default=[
            "Customer size or revenue tier",
            "Geographic location of customer (only shipment location)",
            "Industry sector preferences",
            "Historical relationship length",
            "Any protected characteristics",
        ],
        description="Factors explicitly not considered",
    )
    
    # Human involvement
    human_involvement: str = Field(
        default=(
            "All recommendations require human review before action. "
            "High-value decisions (>$500K) require explicit human approval. "
            "Low-confidence decisions are escalated to human reviewers. "
            "Users can always override AI recommendations."
        ),
        description="Human involvement in process",
    )


class PublicDocumentation(BaseModel):
    """Complete public documentation package."""
    
    # Identity
    version: str = Field(default="1.0.0", description="Documentation version")
    last_updated: datetime = Field(default_factory=datetime.utcnow)
    
    # Components
    ai_disclosure: AIDisclosure = Field(default_factory=AIDisclosure)
    capabilities: SystemCapabilities = Field(default_factory=SystemCapabilities)
    limitations: SystemLimitations = Field(default_factory=SystemLimitations)
    data_usage: DataUsageDisclosure = Field(default_factory=DataUsageDisclosure)
    decision_process: DecisionProcessDocumentation = Field(
        default_factory=DecisionProcessDocumentation
    )
    
    # EU AI Act compliance
    eu_ai_act_classification: str = Field(
        default="LIMITED RISK",
        description="EU AI Act risk classification",
    )
    
    eu_ai_act_statement: str = Field(
        default=(
            "RISKCAST is classified as LIMITED RISK under the EU AI Act. "
            "As such, transparency obligations apply. This documentation fulfills "
            "Article 52 requirements for AI system transparency. Users are informed "
            "that they are interacting with an AI system, and the system's capabilities, "
            "limitations, and decision-making process are documented."
        ),
        description="EU AI Act compliance statement",
    )


class TransparencyReport(BaseModel):
    """Periodic transparency report."""
    
    # Identity
    report_id: str = Field(description="Unique report identifier")
    report_period: str = Field(description="Reporting period (e.g., 'Q1 2025')")
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    
    # Decision statistics
    total_decisions: int = Field(ge=0)
    decisions_with_human_review: int = Field(ge=0)
    decisions_overridden: int = Field(ge=0)
    
    # Accuracy metrics
    accuracy_overall: float = Field(ge=0.0, le=1.0)
    calibration_ece: float = Field(ge=0.0, le=1.0)
    
    # Fairness summary
    fairness_score: float = Field(ge=0.0, le=1.0)
    bias_incidents: int = Field(ge=0)
    
    # Complaints and feedback
    explanation_requests: int = Field(ge=0)
    human_review_requests: int = Field(ge=0)
    complaints: int = Field(ge=0)
    
    # Improvements made
    improvements: List[str] = Field(default_factory=list)
    
    @computed_field
    @property
    def human_review_rate(self) -> float:
        """Percentage of decisions with human review."""
        if self.total_decisions == 0:
            return 0.0
        return self.decisions_with_human_review / self.total_decisions
    
    @computed_field
    @property
    def override_rate(self) -> float:
        """Percentage of decisions overridden."""
        if self.total_decisions == 0:
            return 0.0
        return self.decisions_overridden / self.total_decisions


# ============================================================================
# TRANSPARENCY MANAGER
# ============================================================================


class TransparencyManager:
    """
    Manages transparency documentation and reporting.
    
    Ensures compliance with EU AI Act transparency requirements.
    """
    
    def __init__(self):
        """Initialize transparency manager."""
        self._documentation = PublicDocumentation()
        self._reports: List[TransparencyReport] = []
    
    def get_public_documentation(
        self,
        level: TransparencyLevel = TransparencyLevel.FULL,
    ) -> PublicDocumentation:
        """
        Get public documentation at specified level.
        
        Args:
            level: Level of detail to include
            
        Returns:
            PublicDocumentation appropriate for level
        """
        # For now, return full documentation
        # In production, filter based on level
        return self._documentation
    
    def get_ai_disclosure(self) -> AIDisclosure:
        """Get AI disclosure statement."""
        return self._documentation.ai_disclosure
    
    def get_capabilities(self) -> SystemCapabilities:
        """Get system capabilities documentation."""
        return self._documentation.capabilities
    
    def get_limitations(self) -> SystemLimitations:
        """Get system limitations documentation."""
        return self._documentation.limitations
    
    def get_data_usage(self) -> DataUsageDisclosure:
        """Get data usage disclosure."""
        return self._documentation.data_usage
    
    def get_decision_process(self) -> DecisionProcessDocumentation:
        """Get decision process documentation."""
        return self._documentation.decision_process
    
    async def generate_transparency_report(
        self,
        period: str,
        start_date: datetime,
        end_date: datetime,
    ) -> TransparencyReport:
        """
        Generate transparency report for period.
        
        Args:
            period: Report period name (e.g., "Q1 2025")
            start_date: Period start
            end_date: Period end
            
        Returns:
            TransparencyReport with metrics
        """
        # TODO: Integrate with actual metrics
        # For now, return mock report
        report = TransparencyReport(
            report_id=f"transparency_{datetime.utcnow().strftime('%Y%m%d')}",
            report_period=period,
            total_decisions=1250,
            decisions_with_human_review=312,  # ~25%
            decisions_overridden=45,          # ~3.6%
            accuracy_overall=0.72,
            calibration_ece=0.08,
            fairness_score=0.90,
            bias_incidents=2,
            explanation_requests=28,
            human_review_requests=156,
            complaints=3,
            improvements=[
                "Added 95% and 99% confidence intervals",
                "Improved calibration monitoring with drift detection",
                "Enhanced fairness reporting by customer segment",
                "Added confidence communication guidance",
            ],
        )
        
        self._reports.append(report)
        
        logger.info(
            "transparency_report_generated",
            report_id=report.report_id,
            period=period,
            total_decisions=report.total_decisions,
            accuracy=report.accuracy_overall,
        )
        
        return report
    
    def get_latest_report(self) -> Optional[TransparencyReport]:
        """Get most recent transparency report."""
        if not self._reports:
            return None
        return self._reports[-1]
    
    def generate_markdown_documentation(self) -> str:
        """Generate markdown format documentation."""
        doc = self._documentation
        
        markdown = f"""# RISKCAST AI System Documentation

**Version:** {doc.version}  
**Last Updated:** {doc.last_updated.strftime('%Y-%m-%d')}  
**EU AI Act Classification:** {doc.eu_ai_act_classification}

---

## AI Disclosure

{doc.ai_disclosure.disclosure_text}

**Human Oversight:** {doc.ai_disclosure.human_oversight}

**Contact:** {doc.ai_disclosure.contact_for_questions}

---

## System Capabilities

**Primary Function:** {doc.capabilities.primary_function}

### What RISKCAST Can Do

{chr(10).join(f'- {c}' for c in doc.capabilities.capabilities)}

### Supported Scenarios

{chr(10).join(f'- {s}' for s in doc.capabilities.supported_scenarios)}

### Geographic Coverage

{chr(10).join(f'- {g}' for g in doc.capabilities.geographic_coverage)}

### Data Sources

{chr(10).join(f'- {d}' for d in doc.capabilities.data_sources)}

---

## System Limitations

### Technical Limitations

{chr(10).join(f'- {l}' for l in doc.limitations.technical_limitations)}

### Scope Limitations

{chr(10).join(f'- {l}' for l in doc.limitations.scope_limitations)}

### Not Suitable For

{chr(10).join(f'- {n}' for n in doc.limitations.not_suitable_for)}

---

## How Decisions Are Made

{doc.decision_process.process_overview}

### Decision Factors

{chr(10).join(f'- {f}' for f in doc.decision_process.decision_factors)}

### Factors NOT Considered

{chr(10).join(f'- {n}' for n in doc.decision_process.not_considered)}

### Human Involvement

{doc.decision_process.human_involvement}

---

## Data Usage

### Data We Collect

{chr(10).join(f'- {d}' for d in doc.data_usage.data_collected)}

### How We Use Your Data

{chr(10).join(f'- {p}' for p in doc.data_usage.data_purposes)}

### Your Rights

{chr(10).join(f'- {r}' for r in doc.data_usage.user_rights)}

**Data Retention:** {doc.data_usage.data_retention}

**Data Sharing:** {doc.data_usage.data_sharing}

---

## EU AI Act Compliance

{doc.eu_ai_act_statement}

---

*This documentation is provided to fulfill EU AI Act Article 52 transparency requirements.*
"""
        return markdown


# ============================================================================
# FACTORY
# ============================================================================


_transparency_manager: Optional[TransparencyManager] = None


def get_transparency_manager() -> TransparencyManager:
    """Get global transparency manager (singleton)."""
    global _transparency_manager
    if _transparency_manager is None:
        _transparency_manager = TransparencyManager()
    return _transparency_manager
