"""
RiskCast Outcome Tracking System.

Components:
- schemas: Outcome data models
- recorder: Record actual outcomes for decisions
- accuracy: Prediction vs actual metrics (Brier score, calibration drift)
- flywheel: Feed outcomes back to improve models
- roi: Track value generated by RiskCast decisions
"""
